'use-strict';

// Quiz content
const questions = [
  {
    celebrity: 'images/taylor-swift.jpg',
    choice1: 'Haley Bennett',
    choice2: 'Taylor Swift',
    choice3: 'Leelee Sobieski',
    choice4: 'Shailene Woodley',
    choice5: 'Jennifer Lawrence',
    answer: 'Taylor Swift',
  },
  {
    celebrity: 'images/keanu-reeves.jpg',
    choice1: 'Roman Reigns',
    choice2: 'Jack Matthews',
    choice3: 'Jason Momoa',
    choice4: 'Russell Brand',
    choice5: 'Keanu Reeves',
    answer: 'Keanu Reeves',
  },
  {
    celebrity: 'images/sofia-vergara.jpg',
    choice1: 'Jennifer Lopez',
    choice2: 'Sofía Vergara',
    choice3: 'Jessica Alba',
    choice4: 'Salma Hayek',
    choice5: 'Penélope Cruz',
    answer: 'Sofía Vergara',
  },
  {
    celebrity: 'images/nicki-minaj-2.jpg',
    choice1: 'Cardi B',
    choice2: 'Nicki Minaj',
    choice3: 'Raven Symoné',
    choice4: 'Kylie Jenner',
    choice5: 'Zendaya',
    answer: 'Nicki Minaj',
  },
  {
    celebrity: 'images/johnny-depp.jpg',
    choice1: 'Robert Downey Jr.',
    choice2: 'Omar Metwally',
    choice3: 'Hugh Jackman',
    choice4: 'Johnny Depp',
    choice5: 'Jeffery Dean Morgan',
    answer: 'Johnny Depp',
  },
  {
    celebrity: 'images/elijah-wood.png',
    choice1: 'Elijah Wood',
    choice2: 'Daniel Radcliffe',
    choice3: 'Liam Hemsworth',
    choice4: 'Tobey Maguire',
    choice5: 'Justin Timberlake',
    answer: 'Elijah Wood',
  },
  {
    celebrity: 'images/rihanna-2.jpg',
    choice1: 'Rihanna',
    choice2: 'Megan Fox',
    choice3: 'Cardi B',
    choice4: 'Beyoncé',
    choice5: 'Ally Brooke',
    answer: 'Rihanna',
  },
  {
    celebrity: 'images/anthony-mackie.jpg',
    choice1: 'Anthony Mackie',
    choice2: 'Don Cheadle',
    choice3: 'Jamie Foxx',
    choice4: 'Idris Elba',
    choice5: 'Michael B. Jordan',
    answer: 'Anthony Mackie',
  },
  {
    celebrity: 'images/selena-gomez.jpg',
    choice1: 'Selena Gomez',
    choice2: 'Victoria Justice',
    choice3: 'Ariana Grande',
    choice4: 'Camila Cabello',
    choice5: 'Elizabeth Gillies',
    answer: 'Selena Gomez',
  },
  {
    celebrity: 'images/john-cho.jpg',
    choice1: 'Steven Yeun',
    choice2: 'Harry Shum Jr.',
    choice3: 'Henry Golding',
    choice4: 'John Cho',
    choice5: 'Daniel Henney',
    answer: 'John Cho',
  },
];
